# Databricks notebook source
# MAGIC %md
# MAGIC # Databricks Solution

# COMMAND ----------

#### Read the files ####

from pyspark.sql import functions as F, Window
from pyspark.sql.types import *

BASE = "/Volumes/ecommerce/raw/databricks_dataset"   


# Schemas for the JSON string columns
items_schema = ArrayType(StructType([
    StructField("coupon", StringType()),
    StructField("item_id", StringType()),
    StructField("item_name", StringType()),
    StructField("item_revenue_in_usd", DoubleType()),
    StructField("price_in_usd", DoubleType()),
    StructField("quantity", LongType()),
]))
geo_schema  = StructType([StructField("city", StringType()), StructField("state", StringType())])
ecom_schema = StructType([
    StructField("purchase_revenue_in_usd", DoubleType()),
    StructField("total_item_quantity", LongType()),
    StructField("unique_items", LongType()),
])

## USERS FILE ##
users    = spark.read.csv(f"{BASE}/users.csv",header=True, multiLine=True, nullValue="null",inferSchema=True)

## PRODUCTS FILE ##
products = spark.read.csv(f"{BASE}/products.csv", header=True, multiLine=True, nullValue="null",inferSchema=True)

## SALES FILE ##
sales    = (spark.read.csv(f"{BASE}/sales.csv",header=True, multiLine=True, escape='"',nullValue="null",inferSchema=True)
            .withColumn("items", F.from_json("items", items_schema)))

## EVENTS FILE ##
events   = (spark.read.csv(f"{BASE}/events.csv", header=True, multiLine=True,nullValue="null",escape='"')
            .withColumn("items", F.from_json("items", items_schema))
            .withColumn("geo", F.from_json("geo", geo_schema))
            .withColumn("ecommerce", F.from_json("ecommerce", ecom_schema)))


# Cast epoch-microsecond timestamp columns to real timestamps (in place)
sales  = sales.withColumn("transaction_timestamp",
             (F.col("transaction_timestamp")/1e6).cast("timestamp"))

users  = users.withColumn("user_first_touch_timestamp",
             (F.col("user_first_touch_timestamp")/1e6).cast("timestamp"))

events = (events
    .withColumn("event_timestamp",            (F.col("event_timestamp")/1e6).cast("timestamp"))
    .withColumn("event_previous_timestamp",   (F.col("event_previous_timestamp")/1e6).cast("timestamp"))
    .withColumn("user_first_touch_timestamp", (F.col("user_first_touch_timestamp")/1e6).cast("timestamp")))

# COMMAND ----------

# MAGIC %md
# MAGIC # PART 1 
# MAGIC
# MAGIC ## Data Exploration & Preparation

# COMMAND ----------

# 1. Schema of each table
for name, df in [("users",users),("sales",sales),("products",products),("events",events)]:
    print("--------- ",name, " ------------")
    display(df)

# COMMAND ----------

# 2 & 3. Record count + preview of each table
count_df = spark.createDataFrame ([
    ("users",users.count()),("sales",    sales.count()),
     ("products", products.count()),
     ("events",   events.count())] , ["table", "count"]
                                  
                                  )
display(count_df)



# COMMAND ----------

# MAGIC %md
# MAGIC ## Data Transformation

# COMMAND ----------

# DBTITLE 1,Cell 7
# 1. Flatten Nested Columns: Flatten the items array in the sales and events tables, 
# creating separate columns for each field in the items array. 

print("------","sales_items", " --------")    
sales_items = (sales
    .select("order_id", "email", "transaction_timestamp", F.explode("items").alias("i"))
    .select("order_id", "email", "transaction_timestamp", "i.*"))
display(sales_items)

print("------","event_items", " --------")    
events_items = (events
    .select("user_id", "event_name", "traffic_source", "event_timestamp",
            "geo", "ecommerce", F.explode("items").alias("i"))
    .select("user_id", "event_name", "traffic_source", "event_timestamp",
            F.col("geo.city").alias("city"), F.col("geo.state").alias("state"),
            F.col("ecommerce.purchase_revenue_in_usd").alias("purchase_revenue_in_usd"),
            F.col("ecommerce.total_item_quantity").alias("total_item_quantity"),
            F.col("ecommerce.unique_items").alias("unique_items"),
            "i.*"))
display(events_items)

# COMMAND ----------

# 2. Calculate Revenue per Item: Compute the total revenue generated by each item in the sales table. 

display(sales_items.groupBy("item_id").agg(
    F.round(F.sum("item_revenue_in_usd"), 2).alias("total_revenue")
).orderBy(F.desc("total_revenue")))

# COMMAND ----------

# 3. Add Price to Sales: Join the sales table with the products table on item_id and add the product price to the sales data. 
sales_priced = sales_items.join(
    products.select(F.col("item_id"), F.col("price").alias("product_price")),
    on="item_id", how="left")
display(sales_priced.select("order_id","item_id","quantity","price_in_usd","product_price"))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Joins & Aggregations

# COMMAND ----------

# 1. User Purchase Count: Join the users table with the sales table and compute the total number of purchases each user has made. 
purchases_per_user = (sales.join(users, on="email", how="left")   # keep every sale
    .groupBy("email")
    .agg(F.countDistinct("order_id").alias("num_purchases"))
    .orderBy(F.desc("num_purchases")))
display(purchases_per_user)


# COMMAND ----------

# 2. Revenue by User: Calculate the total revenue generated by each user in the sales table.
revenue_per_user = (sales.groupBy("email")
    .agg(F.round(F.sum("purchase_revenue_in_usd"),2).alias("total_revenue"))
    .orderBy(F.desc("total_revenue")))
display(revenue_per_user)

# COMMAND ----------

# 3. Most Popular Products: Identify the top 10 most frequently purchased items based on the quantity sold in the sales table. 
display(sales_items.groupBy("item_id").agg(
    F.sum("quantity").alias("total_quantity")
).orderBy(F.desc("total_quantity")).limit(10))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Time-Based Analysis

# COMMAND ----------

# 1. First Purchase Timing: Determine the average time between a user’s first touch and their  first purchase

first_touch = (users
    .filter(F.col("email").isNotNull())
    .groupBy("email")
    .agg(F.min("user_first_touch_timestamp").alias("first_touch")))

# first purchase per user
first_purchase = (sales
    .groupBy("email")
    .agg(F.min("transaction_timestamp").alias("first_purchase")))

# hours between first touch and first purchase, per user
touch_to_purchase = (first_purchase
    .join(first_touch, "email", "inner")          # inner: no touch => interval undefined
    .withColumn("hours",
        (F.col("first_purchase").cast("long") - F.col("first_touch").cast("long")) / 3600)
    .withColumn("days", F.round(F.col("hours") / 24, 2)))

# per-user detail
display(touch_to_purchase.withColumnRenamed("email", "user").orderBy(F.desc("hours")))


# display(touch_to_purchase.agg(
#     F.round(F.avg("hours"), 2).alias("avg_hours_touch_to_purchase"),
#     F.round(F.avg("hours") / 24, 2).alias("avg_days_touch_to_purchase"),
#     F.count("*").alias("users_measured")))        

# COMMAND ----------

# 2. Monthly Revenue Trends: Compute the monthly revenue trend over the past year. Include a time series plot of total monthly revenue. 
monthly_rev = (sales
    .groupBy(F.date_format("transaction_timestamp","yyyy-MM").alias("month"))
    .agg(F.round(F.sum("purchase_revenue_in_usd"),2).alias("revenue"))
    .orderBy("month"))
monthly_rev.show()

pdf = monthly_rev.toPandas()
import matplotlib.pyplot as plt
plt.figure(figsize=(8,4))
plt.plot(pdf["month"], pdf["revenue"], marker="o")
plt.title("Monthly Revenue"); plt.xlabel("Month"); plt.ylabel("Revenue (USD)")
plt.xticks(rotation=45); plt.tight_layout(); plt.show()

# COMMAND ----------

# 3. Event Frequency: Count the number of events per month and plot the frequency trend over time
monthly_events = (events
    .groupBy(F.date_format("event_timestamp","yyyy-MM").alias("month"))
    .count().orderBy("month"))
monthly_events.show()

pe = monthly_events.toPandas()
plt.figure(figsize=(8,4))
plt.plot(pe["month"], pe["count"], marker="o", color="green")
plt.title("Events per Month"); plt.xlabel("Month"); plt.ylabel("Event count")
plt.xticks(rotation=45); plt.tight_layout(); plt.show()

# COMMAND ----------

# MAGIC %md
# MAGIC ## User Behavior Analysis

# COMMAND ----------

# 1. Active Users per City: Calculate the number of unique users from each city based on the events table.

display((events.groupBy(F.col("geo.city").alias("city"))
    .agg(F.countDistinct("user_id").alias("active_users"))
    .orderBy(F.desc("active_users"))))

# COMMAND ----------

# 2. Revenue per Traffic Source: Calculate the total revenue generated from each traffic source and sort them in descending order. 
display((events_items.groupBy("traffic_source")
    .agg(F.round(F.sum("item_revenue_in_usd"),2).alias("revenue"))
    .orderBy(F.desc("revenue"))))

# COMMAND ----------

# 3. Average Item Quantity per Purchase: Compute the average number of items purchased per transaction in the sales table. 
display(sales.agg(
    F.count("order_id").alias("total_transactions"),          # 1 row = 1 transaction, confirmed
    F.sum("total_item_quantity").alias("total_items_sold"),
    F.round(F.avg("total_item_quantity"), 4).alias("avg_items_per_transaction")))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Product Analysis

# COMMAND ----------

# 1. High Revenue Products: Identify the top 5 products by total revenue and provide details for these products. 
top5 = (sales_items.groupBy("item_id")
    .agg(F.round(F.sum("item_revenue_in_usd"),2).alias("revenue"))
    .orderBy(F.desc("revenue")).limit(5))
display(top5.join(products, "item_id", "left").select("item_id","name","price","revenue") \
    .orderBy(F.desc("revenue")))

# COMMAND ----------

# 2. Geographic Revenue Distribution: Calculate the total revenue from each state and visualize the distribution. 
import matplotlib.pyplot as plt
state_rev = (events.filter(F.col("geo.state").isNotNull())
    .select(F.col("geo.state").alias("state"), F.explode("items").alias("i"))
    .groupBy("state")
    .agg(F.round(F.sum("i.item_revenue_in_usd"),2).alias("revenue"))
    .orderBy(F.desc("revenue")))
display(state_rev)

ps = state_rev.limit(15).toPandas()
plt.figure(figsize=(9,4))
plt.bar(ps["state"], ps["revenue"])
plt.title("Revenue by State (top 15)"); plt.xlabel("State"); plt.ylabel("Revenue (USD)")
plt.tight_layout(); plt.show()

# COMMAND ----------

# DBTITLE 1,Cell 25
# 3. Event Impact: Analyze how different types of events impact purchase revenue. Determine if there is a significant difference in revenue based on event type

summary = (events
    .withColumn("event_revenue", F.col("ecommerce.purchase_revenue_in_usd"))
    .groupBy("event_name")
    .agg(
        F.count("*").alias("num_events"),
        F.sum(F.when(F.col("event_revenue") > 0, 1).otherwise(0)).alias("events_with_rev"),
        F.round(F.sum("event_revenue"), 2).alias("total_revenue"),
        F.round(F.avg("event_revenue"), 2).alias("avg_rev_per_event"),
        F.round(F.stddev("event_revenue"), 2).alias("stddev_rev")
    )
    .orderBy(F.desc("total_revenue")))
display(summary)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Complex Aggregations & Joins

# COMMAND ----------

# 1. User Purchase Patterns: Compute the average purchase frequency per user. Define purchase frequency as the number of purchases divided by the number of days active

user_freq = (sales.groupBy("email").agg(
        F.countDistinct("order_id").alias("purchases"),
        F.countDistinct(F.to_date("transaction_timestamp")).alias("active_days"),
        F.min("transaction_timestamp").alias("first_purchase"),
        F.max("transaction_timestamp").alias("last_purchase"))
    .withColumn("tenure_days", F.datediff("last_purchase", "first_purchase"))
    .withColumn("purchase_frequency",
        F.round(F.col("purchases") / F.greatest("active_days", F.lit(1)), 4)))
display(user_freq.orderBy(F.desc("purchases"), F.desc("purchase_frequency")))

# COMMAND ----------

# DBTITLE 1,Cell 28
# 2. Items Purchased with Coupons: Determine the total revenue and quantity of items
# purchased with coupons versus those without

coupon_summary = (sales_items
    .withColumn("segment", F.when(F.col("coupon").isNotNull(), "coupon").otherwise("no_coupon"))
    .groupBy("segment")
    .agg(F.round(F.sum("item_revenue_in_usd"), 2).alias("revenue"),
         F.sum("quantity").alias("quantity"),
         F.count("*").alias("line_items"))
    .withColumn("pct_revenue",
        F.round(F.col("revenue") / F.sum("revenue").over(Window.partitionBy()) * 100, 2))
    .withColumn("pct_quantity",
        F.round(F.col("quantity") / F.sum("quantity").over(Window.partitionBy()) * 100, 2))
    .orderBy(F.desc("revenue")))
display(coupon_summary)

# COMMAND ----------

# DBTITLE 1,Cell 29
# 3. Product Purchase Correlation: Analyze the correlation between the number of items
# purchased and the total revenue for each product.

prod_stats = (sales_items.groupBy("item_id").agg(
        F.first("item_name").alias("item_name"),
        F.sum("quantity").alias("qty"),
        F.round(F.sum("item_revenue_in_usd"), 2).alias("rev"),
        F.round(F.avg("price_in_usd"), 2).alias("avg_price"))
    .orderBy(F.desc("rev")))
display(prod_stats)

prod_corr = prod_stats.stat.corr("qty", "rev")
line_corr = sales_items.stat.corr("quantity", "item_revenue_in_usd")
print(f"corr(qty, rev) across {prod_stats.count()} products = {prod_corr:.4f}")   
print(f"corr at line-item grain (n={sales_items.count()})   = {line_corr:.4f}")



# COMMAND ----------

# MAGIC %md
# MAGIC ## Advanced Metrics

# COMMAND ----------

# DBTITLE 1,Cell 31
# 1. Customer Lifetime Value (CLV): Estimate the Customer Lifetime Value for each user
# based on their purchase history  CLV = total revenue; enriched with orders count, avg order value, and active span.

clv = (sales.groupBy("email")
    .agg(
        F.round(F.sum("purchase_revenue_in_usd"), 2).alias("clv"),
        F.countDistinct("order_id").alias("orders"),
        F.round(F.avg("purchase_revenue_in_usd"), 2).alias("avg_order_value"),
        F.datediff(
            F.max("transaction_timestamp"),
            F.min("transaction_timestamp")
        ).alias("active_days")
    )
    .orderBy(F.desc("clv")))

display(clv)

# COMMAND ----------

# 2. Conversion Rate Analysis: Determine the conversion rate for users who interacted with different traffic sources.
visitors = events.groupBy("traffic_source").agg(F.countDistinct("user_id").alias("visitors"))
buyers   = (events.filter(F.col("event_name")=="finalize")
            .groupBy("traffic_source").agg(F.countDistinct("user_id").alias("buyers")))
display((visitors.join(buyers, "traffic_source", "left")
    .withColumn("conversion_rate",
        F.round(F.coalesce("buyers", F.lit(0))/F.col("visitors"), 4))
    .orderBy(F.desc("conversion_rate"))))

# COMMAND ----------

# 3. Churn Analysis: Identify users who have not made a purchase in the last 6 months and analyze the characteristics of these users

latest = sales.agg(F.max("transaction_timestamp")).first()[0]

recency = (sales.groupBy("email")
    .agg(F.max("transaction_timestamp").alias("last_purchase"),
         F.round(F.sum("purchase_revenue_in_usd"), 2).alias("revenue"))
    .withColumn("days_since_last", F.datediff(F.lit(latest), "last_purchase")))

CHURN_DAYS = 180  # parameterized; override for short datasets
churned = recency.filter(F.col("days_since_last") >= CHURN_DAYS)
print(f"latest={latest} | window={CHURN_DAYS}d | churned={churned.count()}")  # 0 on this data

# Characteristic analysis via recency buckets (works on the short window)
buckets = (recency
    .withColumn("recency_bucket",
        F.when(F.col("days_since_last") <= 7, "0-7d")
         .when(F.col("days_since_last") <= 14, "8-14d")
         .otherwise("15d+"))
    .groupBy("recency_bucket")
    .agg(F.count("*").alias("users"),
         F.round(F.avg("revenue"), 2).alias("avg_revenue"))
    .orderBy("recency_bucket"))
display(buckets)
